// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: event_performers.sql

package entities

import (
	"context"

	"github.com/google/uuid"
)

const addPerformerToEvent = `-- name: AddPerformerToEvent :one
INSERT INTO event_performers (event_id, performer_id)
VALUES ($1, $2)
RETURNING id, event_id, performer_id
`

type AddPerformerToEventParams struct {
	EventID     uuid.UUID `json:"event_id"`
	PerformerID uuid.UUID `json:"performer_id"`
}

func (q *Queries) AddPerformerToEvent(ctx context.Context, arg AddPerformerToEventParams) (EventPerformer, error) {
	row := q.db.QueryRow(ctx, addPerformerToEvent, arg.EventID, arg.PerformerID)
	var i EventPerformer
	err := row.Scan(&i.ID, &i.EventID, &i.PerformerID)
	return i, err
}
