// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package entities

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID         uuid.UUID        `json:"id"`
	UserID     uuid.UUID        `json:"user_id"`
	TicketID   uuid.UUID        `json:"ticket_id"`
	Quantity   int32            `json:"quantity"`
	TotalPrice pgtype.Numeric   `json:"total_price"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Event struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	AddedBy *uuid.UUID        `json:"added_by"`
	VenueID     uuid.UUID        `json:"venue_id"`
	EventDate   pgtype.Timestamp `json:"event_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type EventPerformer struct {
	ID          uuid.UUID `json:"id"`
	EventID     uuid.UUID `json:"event_id"`
	PerformerID uuid.UUID `json:"performer_id"`
}

type Payment struct {
	ID            uuid.UUID        `json:"id"`
	BookingID     uuid.UUID        `json:"booking_id"`
	UserID        uuid.UUID        `json:"user_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	PaymentMethod string           `json:"payment_method"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Performer struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Genre     string           `json:"genre"`
	Bio       string           `json:"bio"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Ticket struct {
	ID               uuid.UUID        `json:"id"`
	EventID          uuid.UUID        `json:"event_id"`
	TicketType       string           `json:"ticket_type"`
	Price            pgtype.Numeric   `json:"price"`
	TotalTickets     int32            `json:"total_tickets"`
	AvailableTickets int32            `json:"available_tickets"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Phone     pgtype.Text      `json:"phone"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	LastLogin pgtype.Timestamp `json:"last_login"`
}

type Venue struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Location  string           `json:"location"`
	Capacity  int32            `json:"capacity"`
	AddedBy *uuid.UUID        `json:"added_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
