// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payments.sql

package entities

import (
	"context"

	"github.com/google/uuid"
)

const confirmPayment = `-- name: ConfirmPayment :exec
WITH updated_payment AS (
    UPDATE payments
    SET status = 'completed'
    WHERE payments.id = $1 AND status = 'pending'
    RETURNING booking_id
)
UPDATE bookings
SET status = 'confirmed'
WHERE bookings.id = (SELECT booking_id FROM updated_payment)
`

func (q *Queries) ConfirmPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmPayment, id)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, user_id, amount, payment_method, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, booking_id, user_id, amount, payment_method, status, created_at
`

type CreatePaymentParams struct {
	BookingID     uuid.UUID  `json:"booking_id"`
	UserID        *uuid.UUID `json:"user_id"`
	Amount        float64    `json:"amount"`
	PaymentMethod string     `json:"payment_method"`
	Status        string     `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.UserID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.UserID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const failPayment = `-- name: FailPayment :exec
WITH updated_payment AS (
    UPDATE payments
    SET status = 'failed'
    WHERE payments.id = $1 AND status = 'pending'
    RETURNING booking_id
)
UPDATE bookings
SET status = 'canceled'
WHERE bookings.id = (SELECT booking_id FROM updated_payment)
`

func (q *Queries) FailPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failPayment, id)
	return err
}
